import express from 'express';
import mysql from 'mysql2/promise';
import {randomUUID,randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {ensureAlertSchema, syncReadingAlerts, installAlertRoutes, dashboardAlerts} from './alerts.js';
import {ensureOnboardingSchema, installOnboardingRoutes} from './onboarding.js';
import {ensureMediaSchema, installMediaRoutes} from './media.js';

const app=express(),pool=mysql.createPool({host:process.env.MYSQL_HOST||'127.0.0.1',port:Number(process.env.MYSQL_PORT||3306),user:process.env.MYSQL_USER||'cafp',password:process.env.MYSQL_PASSWORD||'',database:process.env.MYSQL_DATABASE||'cafp',waitForConnections:true,connectionLimit:10,dateStrings:true});
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../dist');
app.disable('x-powered-by');app.use(express.json({limit:'4mb'}));
app.use('/api',(req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const origin=req.get('origin');const host=req.get('host');if(origin&&new URL(origin).host!==host)return res.status(403).json({error:'Origin mismatch'});}next()});
const query=(sql,args=[])=>pool.execute(sql,args).then(([rows])=>rows);
const hash=s=>createHash('sha256').update(s).digest('hex');
function passwordHash(password){const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`}
function checkPassword(password,stored){const [salt,digest]=stored.split(':');if(!salt||!digest)return false;const actual=scryptSync(password,salt,64),expected=Buffer.from(digest,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected)}
function fail(res,status,message){return res.status(status).json({error:message})}
function cookie(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function setCookie(res,token){res.setHeader('Set-Cookie',`cafp_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.COOKIE_SECURE==='true'?'; Secure':''}`)}
async function auth(req,res,next){try{const token=cookie(req).cafp_session;if(!token)return fail(res,401,'Sign in required');const rows=await query('SELECT u.id,u.tenant_id,u.email,u.name,u.role,u.active,t.name tenant_name FROM sessions s JOIN users u ON u.id=s.user_id JOIN tenants t ON t.id=u.tenant_id WHERE s.token_hash=? AND s.expires_at>NOW()',[hash(token)]);if(!rows[0]?.active)return fail(res,401,'Session expired');req.user=rows[0];next()}catch(e){next(e)}}
const requireRole=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():fail(res,403,'Insufficient role');
const audit=(u,action,entity,id)=>query('INSERT INTO audit_events (tenant_id,actor_id,action,entity,entity_id) VALUES (?,?,?,?,?)',[u.tenant_id,u.id,action,entity,id]);
const validEmail=x=>typeof x==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)&&x.length<=255;
const validPassword=x=>typeof x==='string'&&x.length>=12&&x.length<=128;
const id=x=>typeof x==='string'&&/^[0-9a-f-]{36}$/i.test(x);
const numeric=(x,min,max)=>x===null||x===''||x===undefined?null:Number.isFinite(Number(x))&&Number(x)>=min&&Number(x)<=max?Number(x):NaN;
const dataUrl=x=>typeof x==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(x)&&x.length<3_000_000;
const recordShape=r=>({id:r.id,type:r.type,plot:r.plot_id,device:r.device_id,time:r.observed_at.replace(' ','T')+'Z',moisture:r.moisture??'',temperature:r.temperature??'',humidity:r.humidity??'',note:r.note??'',photo:r.photo??'',source:r.source});

app.post('/api/auth/register',async(req,res,next)=>{let {farm,name,email,password}=req.body||{};if(!farm?.trim()||!name?.trim()||!validEmail(email)||!validPassword(password))return fail(res,400,'Farm, name, valid email and password of at least 12 characters required');const c=await pool.getConnection();try{await c.beginTransaction();let tenant=randomUUID(),user=randomUUID();await c.execute('INSERT INTO tenants (id,name) VALUES (?,?)',[tenant,farm.trim().slice(0,160)]);await c.execute('INSERT INTO users (id,tenant_id,email,name,password_hash,role) VALUES (?,?,?,?,?,?)',[user,tenant,email.trim().toLowerCase(),name.trim().slice(0,160),passwordHash(password),'owner']);await c.execute('INSERT INTO tenant_settings (tenant_id) VALUES (?)',[tenant]);await c.commit();const token=randomBytes(32).toString('hex');await query('INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 7 DAY))',[hash(token),user]);setCookie(res,token);res.status(201).json({user:{id:user,tenant_id:tenant,name,email,role:'owner',tenant_name:farm}})}catch(e){await c.rollback();next(e)}finally{c.release()}});
app.post('/api/auth/login',async(req,res,next)=>{try{let {email,password,farm}=req.body||{};if(!validEmail(email)||!password||!farm?.trim())return fail(res,400,'Farm name, email and password required');let rows=await query('SELECT u.*,t.name tenant_name FROM users u JOIN tenants t ON t.id=u.tenant_id WHERE u.email=? AND t.name=? AND u.active=1',[email.trim().toLowerCase(),farm.trim()]);let u=rows.find(x=>checkPassword(password,x.password_hash));if(!u)return fail(res,401,'Invalid credentials');const token=randomBytes(32).toString('hex');await query('INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 7 DAY))',[hash(token),u.id]);setCookie(res,token);res.json({user:{id:u.id,tenant_id:u.tenant_id,name:u.name,email:u.email,role:u.role,tenant_name:u.tenant_name}})}catch(e){next(e)}});
app.post('/api/auth/logout',auth,async(req,res,next)=>{try{await query('DELETE FROM sessions WHERE token_hash=?',[hash(cookie(req).cafp_session)]);res.setHeader('Set-Cookie','cafp_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true})}catch(e){next(e)}});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/dashboard',auth,async(req,res,next)=>{try{let t=req.user.tenant_id;const [plots,devices,records,settings,alerts]=await Promise.all([query('SELECT id,name,crop,area FROM plots WHERE tenant_id=? ORDER BY name',[t]),query('SELECT id,plot_id,label,kind,status,last_seen_at FROM devices WHERE tenant_id=? ORDER BY label',[t]),query('SELECT * FROM records WHERE tenant_id=? ORDER BY observed_at DESC LIMIT 500',[t]),query('SELECT low_moisture low,high_temperature high FROM tenant_settings WHERE tenant_id=?',[t]),dashboardAlerts(pool,t)]);let s=settings[0]||{low:20,high:35};res.json({plots,devices,records:records.map(recordShape),settings:s,alerts,summary:{plots:plots.length,devices:devices.length,readings:records.filter(r=>r.type==='reading').length,photos:records.filter(r=>r.type==='photo').length,alerts:alerts.length}})}catch(e){next(e)}});
app.get('/api/plots',auth,async(req,res,next)=>{try{res.json(await query('SELECT * FROM plots WHERE tenant_id=? ORDER BY name',[req.user.tenant_id]))}catch(e){next(e)}});
app.post('/api/plots',auth,requireRole('owner','admin','operator'),async(req,res,next)=>{try{let {name,crop='',area=''}=req.body||{};if(!name?.trim())return fail(res,400,'Plot name required');let key=randomUUID();await query('INSERT INTO plots (id,tenant_id,name,crop,area) VALUES (?,?,?,?,?)',[key,req.user.tenant_id,name.trim().slice(0,160),String(crop).slice(0,120),String(area).slice(0,80)]);await audit(req.user,'create','plot',key);res.status(201).json({id:key})}catch(e){next(e)}});
app.put('/api/plots/:id',auth,requireRole('owner','admin','operator'),async(req,res,next)=>{try{let {name,crop='',area=''}=req.body||{};if(!name?.trim())return fail(res,400,'Plot name required');let r=await query('UPDATE plots SET name=?,crop=?,area=? WHERE id=? AND tenant_id=?',[name.trim().slice(0,160),String(crop).slice(0,120),String(area).slice(0,80),req.params.id,req.user.tenant_id]);if(!r.affectedRows)return fail(res,404,'Plot not found');await audit(req.user,'update','plot',req.params.id);res.json({ok:true})}catch(e){next(e)}});
app.delete('/api/plots/:id',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let count=await query('SELECT COUNT(*) n FROM records WHERE plot_id=? AND tenant_id=?',[req.params.id,req.user.tenant_id]);if(count[0].n)return fail(res,409,'Plot has records; delete its records first');let r=await query('DELETE FROM plots WHERE id=? AND tenant_id=?',[req.params.id,req.user.tenant_id]);if(!r.affectedRows)return fail(res,404,'Plot not found');await audit(req.user,'delete','plot',req.params.id);res.json({ok:true})}catch(e){if(e.code==='ER_ROW_IS_REFERENCED_2')return fail(res,409,'Plot has records; delete its records first');next(e)}});
app.get('/api/devices',auth,async(req,res,next)=>{try{res.json(await query('SELECT id,plot_id,label,kind,status,last_seen_at FROM devices WHERE tenant_id=? ORDER BY label',[req.user.tenant_id]))}catch(e){next(e)}});
app.post('/api/devices',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let {label,kind='sensor',plot=null}=req.body||{};if(!label?.trim()||!['sensor','camera','gateway'].includes(kind))return fail(res,400,'Valid label and kind required');if(plot&&!(await query('SELECT id FROM plots WHERE id=? AND tenant_id=?',[plot,req.user.tenant_id])).length)return fail(res,404,'Plot not found');let key=randomUUID(),secret=randomBytes(24).toString('hex');await query('INSERT INTO devices (id,tenant_id,plot_id,label,kind,api_key_hash) VALUES (?,?,?,?,?,?)',[key,req.user.tenant_id,plot||null,label.trim().slice(0,160),kind,hash(secret)]);await audit(req.user,'create','device',key);res.status(201).json({id:key,apiKey:`${key}.${secret}`})}catch(e){next(e)}});
app.put('/api/devices/:id',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let {label,kind,status,plot}=req.body||{};if(!label?.trim()||!['sensor','camera','gateway'].includes(kind)||!['online','offline','maintenance'].includes(status))return fail(res,400,'Invalid device');if(plot&&!(await query('SELECT id FROM plots WHERE id=? AND tenant_id=?',[plot,req.user.tenant_id])).length)return fail(res,404,'Plot not found');let r=await query('UPDATE devices SET label=?,kind=?,status=?,plot_id=? WHERE id=? AND tenant_id=?',[label.trim().slice(0,160),kind,status,plot||null,req.params.id,req.user.tenant_id]);if(!r.affectedRows)return fail(res,404,'Device not found');await audit(req.user,'update','device',req.params.id);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/devices/:id/rotate-key',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let secret=randomBytes(24).toString('hex'),r=await query('UPDATE devices SET api_key_hash=? WHERE id=? AND tenant_id=?',[hash(secret),req.params.id,req.user.tenant_id]);if(!r.affectedRows)return fail(res,404,'Device not found');await audit(req.user,'rotate-key','device',req.params.id);res.json({apiKey:`${req.params.id}.${secret}`})}catch(e){next(e)}});
app.delete('/api/devices/:id',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let r=await query('DELETE FROM devices WHERE id=? AND tenant_id=?',[req.params.id,req.user.tenant_id]);if(!r.affectedRows)return fail(res,404,'Device not found');await audit(req.user,'delete','device',req.params.id);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/records',auth,async(req,res,next)=>{try{let args=[req.user.tenant_id],sql='SELECT * FROM records WHERE tenant_id=?';if(req.query.plot){sql+=' AND plot_id=?';args.push(req.query.plot)}if(req.query.type){if(!['reading','photo'].includes(req.query.type))return fail(res,400,'Invalid type');sql+=' AND type=?';args.push(req.query.type)}sql+=' ORDER BY observed_at DESC LIMIT 1000';res.json((await query(sql,args)).map(recordShape))}catch(e){next(e)}});
async function insertRecord(user,body,source='manual',device=null){let {plot,type,time,moisture,temperature,humidity,note='',photo=''}=body;if(!id(plot)||!['reading','photo'].includes(type)||!time||isNaN(Date.parse(time)))throw Object.assign(Error('Invalid record details'),{status:400});if(!(await query('SELECT id FROM plots WHERE id=? AND tenant_id=?',[plot,user.tenant_id])).length)throw Object.assign(Error('Plot not found'),{status:404});let m=numeric(moisture,0,100),temp=numeric(temperature,-50,70),h=numeric(humidity,0,100);if([m,temp,h].some(Number.isNaN)||type==='photo'&&!dataUrl(photo)||type==='reading'&&m===null&&temp===null&&h===null)throw Object.assign(Error('Invalid measurement or photo'),{status:400});let key=randomUUID();await query('INSERT INTO records (id,tenant_id,plot_id,device_id,type,observed_at,moisture,temperature,humidity,note,photo,source,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[key,user.tenant_id,plot,device,type,new Date(time).toISOString().slice(0,19).replace('T',' '),m,temp,h,String(note).slice(0,5000),type==='photo'?photo:null,source,user.id||null]);if(type==='reading')await syncReadingAlerts(pool,{tenantId:user.tenant_id,plotId:plot,recordId:key,reading:{moisture:m,temperature:temp}});return key}
app.post('/api/records',auth,requireRole('owner','admin','operator'),async(req,res,next)=>{try{let key=await insertRecord(req.user,req.body);await audit(req.user,'create','record',key);res.status(201).json({id:key})}catch(e){next(e)}});
app.delete('/api/records/:id',auth,requireRole('owner','admin','operator'),async(req,res,next)=>{try{let r=await query('DELETE FROM records WHERE id=? AND tenant_id=?',[req.params.id,req.user.tenant_id]);if(!r.affectedRows)return fail(res,404,'Record not found');await audit(req.user,'delete','record',req.params.id);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/records/import',auth,requireRole('owner','admin','operator'),async(req,res,next)=>{try{let items=req.body?.records;if(!Array.isArray(items)||items.length>500)return fail(res,400,'Provide up to 500 records');let ok=0,errors=[];for(let i=0;i<items.length;i++){try{await insertRecord(req.user,{...items[i],type:'reading'},'CSV import');ok++}catch(e){errors.push({row:i+1,error:e.message})}}res.json({imported:ok,errors})}catch(e){next(e)}});
app.get('/api/settings',auth,async(req,res,next)=>{try{res.json((await query('SELECT low_moisture low,high_temperature high FROM tenant_settings WHERE tenant_id=?',[req.user.tenant_id]))[0])}catch(e){next(e)}});
app.put('/api/settings',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let low=numeric(req.body.low,0,100),high=numeric(req.body.high,-50,70);if(low===null||high===null||Number.isNaN(low)||Number.isNaN(high))return fail(res,400,'Invalid threshold');await query('UPDATE tenant_settings SET low_moisture=?,high_temperature=? WHERE tenant_id=?',[low,high,req.user.tenant_id]);await audit(req.user,'update','settings',req.user.tenant_id);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/users',auth,requireRole('owner','admin'),async(req,res,next)=>{try{res.json(await query('SELECT id,email,name,role,active,created_at FROM users WHERE tenant_id=? ORDER BY name',[req.user.tenant_id]))}catch(e){next(e)}});
app.post('/api/users',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let {email,name,password,role='viewer'}=req.body||{};if(!validEmail(email)||!name?.trim()||!validPassword(password)||!['admin','operator','viewer'].includes(role)||req.user.role==='admin'&&role==='admin')return fail(res,400,'Invalid team member');let key=randomUUID();await query('INSERT INTO users (id,tenant_id,email,name,password_hash,role) VALUES (?,?,?,?,?,?)',[key,req.user.tenant_id,email.trim().toLowerCase(),name.trim().slice(0,160),passwordHash(password),role]);await audit(req.user,'create','user',key);res.status(201).json({id:key})}catch(e){next(e)}});
app.put('/api/users/:id',auth,requireRole('owner','admin'),async(req,res,next)=>{try{let {name,role,active,password}=req.body||{};let target=(await query('SELECT * FROM users WHERE id=? AND tenant_id=?',[req.params.id,req.user.tenant_id]))[0];if(!target)return fail(res,404,'User not found');if(target.role==='owner'||req.user.role==='admin'&&(role==='admin'||target.role==='admin')||!['admin','operator','viewer'].includes(role)||!name?.trim()||target.id===req.user.id&&active===false)return fail(res,403,'Role change not allowed');if(password&&!validPassword(password))return fail(res,400,'Password must be at least 12 characters');await query('UPDATE users SET name=?,role=?,active=?,password_hash=? WHERE id=? AND tenant_id=?',[name.trim().slice(0,160),role,Boolean(active),password?passwordHash(password):target.password_hash,target.id,req.user.tenant_id]);if(!active||password)await query('DELETE FROM sessions WHERE user_id=?',[target.id]);await audit(req.user,'update','user',target.id);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/audit',auth,requireRole('owner','admin'),async(req,res,next)=>{try{res.json(await query('SELECT action,entity,entity_id,created_at FROM audit_events WHERE tenant_id=? ORDER BY id DESC LIMIT 100',[req.user.tenant_id]))}catch(e){next(e)}});
app.post('/api/ingest',async(req,res,next)=>{try{let token=req.get('x-device-key')||'', [deviceId,secret]=token.split('.');if(!id(deviceId)||!secret)return fail(res,401,'Device key required');let d=(await query('SELECT * FROM devices WHERE id=?',[deviceId]))[0];if(!d||!timingSafeEqual(Buffer.from(hash(secret)),Buffer.from(d.api_key_hash)))return fail(res,401,'Invalid device key');let key=await insertRecord({tenant_id:d.tenant_id,id:null},{...req.body,plot:d.plot_id,type:'reading'},'IoT device',d.id);await query("UPDATE devices SET last_seen_at=NOW(),status='online' WHERE id=?",[d.id]);res.status(201).json({id:key})}catch(e){next(e)}});
installAlertRoutes(app,pool,auth,requireRole,audit);
installOnboardingRoutes(app,pool,{auth,requireRole,audit,passwordHash,checkPassword,setCookie});
installMediaRoutes(app,pool,{auth,requireRole,audit});
app.use('/api',(req,res)=>fail(res,404,'API route not found'));
app.use(express.static(root,{index:'index.html'}));app.get('*',(req,res)=>res.sendFile(path.join(root,'index.html')));
app.use((err,req,res,next)=>{console.error(err);if(err.code==='ER_DUP_ENTRY')return fail(res,409,'A record with this value already exists');fail(res,err.status||500,err.status?err.message:'Server error')});
Promise.all([ensureAlertSchema(pool),ensureOnboardingSchema(pool),ensureMediaSchema(pool)]).then(()=>app.listen(Number(process.env.PORT||8080),()=>console.log(`CAFP listening on ${process.env.PORT||8080}`))).catch(error=>{console.error('Database initialization failed',error);process.exit(1)});
